question = [
    "Quel célèbre dictateur dirigea l’URSS du milieu des années 1920 à 1953 ?",
    "Dans quel pays peut-on trouver la Castille",
    "Quel est le nom du personnage principal de l'Oeuvre one piece",
    "Combien de couleur différente y a t-il sur le drapeau de l'afrique du sud",
    "combien font 12*9",
    "Qui a dit le sort en est jeté (alea jacta est)",
    "qui a réalisé titanic ?",
    "Mon premier est la capitale de l’Italie., Mon second est une voyelle., Mon troisième est un fleuve d’Europe., Mon tout est une plante qui sent bon.",
    "Quel nom porte l’habitat du castor ?",
    "Quel est le 6e Président de la Ve République française ?",
    "Quelle est, à ce jour, la plus grande catastrophe nucléaire de l'histoire de l’humanité ?",
    "Quelle est la capitale de la Suisse ?",
    "Quel chanteur ou chanteuse est l’interprète de Shape Of You, sorti en 2017 ? ",
    "À quel peintre attribue-t-on l’Origine du Monde ?",
    "Quel animal tue le plus d'hommes chaque année ? ",
    "Quel est le langage informatique le plus utilisé au monde en 2022 ?",
    "Complétez l'expression :Mettre du beurre dans les...",
    "Comment appelle-t-on l'explosion qui serait à l'origine de l'expansion de l'Univers ?",
    "Comment s'appelle l'ami lapin de Bambi ?",
    "Que signifie en français le mot Guten Tag",
    "Dans quelle articulation du corps humain se situe la rotule ?",
]

reponse = [
    ["staline"],
    ["espagne", "l'espagne"],
    ["luffy", "monkey d luffy"],
    ["6", "six"],
    ["108"],
    ["jules", "jules césar", "jules cesar", "cesar", "césar"],
    ["james cameron", "cameron", "james"],
    ["romarin", "le romarin", "romearhin"],
    ["une hutte", "hutte"],
    ["nicolas sarcozi", "sarcozi", "nicolas"],
    ["tchernobyl"],
    ["berne"],
    ["ed sheeran", "edsheeran", "ed", "sheeran"],
    ["gustave courbet", "courbet", "gustave"],
    ["le moustique", "moustique"],
    ["java", "le java"],
    ["epindards", "épinards"],
    ["le big bang", "big bang"],
    ["pan pan"],
    ["bonjour"],
    ["le genou", "genou"],
]
